// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOEgyjp9Jeznj89p1ALGyT2Y56_5bFnpo',
    appId: '1:7794540354:web:a243bdbad7a0d3941312db',
    messagingSenderId: '7794540354',
    projectId: 'student-loan-manager',
    authDomain: 'student-loan-manager.firebaseapp.com',
    storageBucket: 'student-loan-manager.firebasestorage.app',
    measurementId: 'G-ZSHXZQ9TB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNosnhk6M-exnkkOnQXhuDMSaeOFEQ5k',
    appId: '1:7794540354:android:843f1927adfd6e8f1312db',
    messagingSenderId: '7794540354',
    projectId: 'student-loan-manager',
    storageBucket: 'student-loan-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtckKT2vVx-MY3qMHpbt_iZ3Ujn-rHdpA',
    appId: '1:7794540354:ios:d9e4b138857275d11312db',
    messagingSenderId: '7794540354',
    projectId: 'student-loan-manager',
    storageBucket: 'student-loan-manager.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtckKT2vVx-MY3qMHpbt_iZ3Ujn-rHdpA',
    appId: '1:7794540354:ios:d9e4b138857275d11312db',
    messagingSenderId: '7794540354',
    projectId: 'student-loan-manager',
    storageBucket: 'student-loan-manager.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOEgyjp9Jeznj89p1ALGyT2Y56_5bFnpo',
    appId: '1:7794540354:web:a78a3f1bb7a19ffb1312db',
    messagingSenderId: '7794540354',
    projectId: 'student-loan-manager',
    authDomain: 'student-loan-manager.firebaseapp.com',
    storageBucket: 'student-loan-manager.firebasestorage.app',
    measurementId: 'G-J84J2S2HM6',
  );
}
